---
swagger: '2.0'
info:
  version: 1.0.0
  title: Inventory
basePath: /api
paths:
  /spells:
    x-swagger-router-controller: spells-controller
    get:
      tags:
        - spell
      operationId: all
      summary: Get all spells
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Spell"
    post:
      tags:
        - spell
      operationId: insert
      summary: Insert a new spell
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Spell"
      responses:
        200:
          description: OK

  /spells/{id}:
    x-swagger-router-controller: spells-controller
    get:
      tags:
        - spell
      operationId: one
      summary: Get a spell by id
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: The id of a specific spell
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Spell"
    patch:
      tags:
        - spell
      operationId: modify
      summary: Update a spell
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: The id of a specific spell
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/PatchRequest"
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/Spell"
definitions:
  PatchRequest:
    type: array
    items:
      $ref: "#/definitions/PatchDocument"
  PatchDocument: 
    description: A JSONPatch document as defined by RFC 6902 
    required:
     - op
     - path
    properties: 
     op: 
      type: string 
      description: The operation to be performed 
      enum:
       - add
       - remove
       - replace
       - move
       - copy
       - test
     path: 
      type: string 
      description: A JSON-Pointer 
     value: 
      type: object 
      description: The value to be used within the operations.
     from: 
      type: string 
      description: A string containing a JSON Pointer value.
  Spell:
    type: object
    properties:
      name:
        type: string
      points:
        type: number
    required:
      - name
      - points